apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener-interceptor
spec:
  triggers:
    - name: foo-trig
      interceptors:
        - webhook:
            header:
              - name: Slack-Decodeprefix
                value: slack
            objectRef:
              kind: Service
              name: slack-webhook-interceptor
              apiVersion: v1
              namespace: default
        - cel:
            filter: body.slack.command == '/build'
            overlays:
            - key: slack.repo
              expression: "body.slack.text.split(' ')[0]"
            - key: slack.sha
              expression: "body.slack.text.split(' ')[1]"
            - key: slack.command
              expression: "body.slack.command.split('/')[1]"
      bindings:
        - name: task-run-binding
      template:
        name: task-run-template
