apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: slack-webhook-task
spec:
  inputs:
    params:
    - name: command
      description: the command from slack
    - name: repo
      description: the repo to process
    - name: sha
      description: the specific SHA in the repo
  steps:
  - image: registry.access.redhat.com/ubi8/ubi-minimal
    script: |
        #!/usr/bin/env bash
        echo $(inputs.params.command) $(inputs.params.repo) $(inputs.params.sha)
