apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: task-run-template
spec:
  params:
  - name: command
    description: The command from slack
  - name: repo
    description: The repo to process.
  - name: sha
    description: The specific commit (SHA) to process.
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: TaskRun
    metadata:
      generateName: slack-task-run-
    spec:
      taskRef:
        name: slack-webhook-task
      inputs:
        params:
        - name: command
          value: $(params.command)
        - name: repo
          value: $(params.repo)
        - name: sha
          value: $(params.sha)
