apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-webhook-interceptor
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: slack-webhook-interceptor
  template:
    metadata:
     labels:
       app.kubernetes.io/name: slack-webhook-interceptor
    spec:
      serviceAccountName: default
      containers:
        - name: slack-webhook-interceptor
          image: PATH_TO_IMAGE
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: slack-webhook-interceptor
  namespace: default
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: slack-webhook-interceptor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
